# Generated by Django 3.2.5 on 2021-07-24 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(default=uuid.uuid1, max_length=50, unique=True),
        ),
    ]
